#include "raylib.h"

#include <ctype.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "levels.h"
#include "bricks.h"


int musicThemeIndex(int level)
{
    if (level < 1)
        level = 1;
    if (level > TOTAL_LEVELS)
        level = TOTAL_LEVELS;
    return (level - 1) % MUSIC_THEMES;
}

float levelSpeedScale(int level)
{
    if (level < 1)
        level = 1;
    if (level > TOTAL_LEVELS)
        level = TOTAL_LEVELS;

    return 1.0f + 0.06f * (float)(level - 1);
}

const char *levelName(int level)
{
    static const char *names[TOTAL_LEVELS] = {
        "ENCHANTED CHESS CHAMBER",
        "CHAMBER OF SECRETS",
        "PATRONUS LAKESIDE",
        "TRIWIZARD DRAGON",
        "HALL OF PROPHECY",
        "HORCRUX CAVE",
        "BATTLE OF HOGWARTS"};

    if (level < 1 || level > TOTAL_LEVELS)
        return "UNKNOWN CHAMBER";
    return names[level - 1];
}


void makeLevel(Brick bricks[ROWS][COLS], int level)
{
    clearBricks(bricks);


    const float sideMargin = 18.0f;
    const float gapX = 8.0f;
    const float gapY = 6.0f;
    const float bw = (SCREEN_W - 2.0f * sideMargin - (COLS - 1) * gapX) / COLS;
    const float bh = bw / 3.65f;


    const float startY = 68.0f;

    const float gridW = COLS * bw + (COLS - 1) * gapX;
    const float startX = (SCREEN_W - gridW) / 2.0f;


    static const BrickType layout1[ROWS][COLS] = {

        {BRICK_RED, BRICK_RED, BRICK_NONE, BRICK_NONE, BRICK_BLUE,
         BRICK_BLUE, BRICK_NONE, BRICK_NONE, BRICK_GREEN, BRICK_GREEN},

        {BRICK_RED, BRICK_RED, BRICK_NONE, BRICK_NONE, BRICK_BLUE,
         BRICK_BLUE, BRICK_NONE, BRICK_NONE, BRICK_GREEN, BRICK_GREEN},

        {BRICK_RED, BRICK_RED, BRICK_BLUE, BRICK_BLUE, BRICK_GREEN,
         BRICK_GREEN, BRICK_YELLOW, BRICK_YELLOW, BRICK_PURPLE, BRICK_PURPLE},

        {BRICK_NONE, BRICK_RED, BRICK_BLUE, BRICK_BLUE, BRICK_GREEN,
         BRICK_GREEN, BRICK_YELLOW, BRICK_YELLOW, BRICK_PURPLE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_GREEN, BRICK_GREEN, BRICK_YELLOW,
         BRICK_YELLOW, BRICK_PURPLE, BRICK_PURPLE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_FIRE, BRICK_FIRE, BRICK_LIGHTNING,
         BRICK_LIGHTNING, BRICK_ICE, BRICK_ICE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE}};


    static const BrickType layout2[ROWS][COLS] = {

        {BRICK_NONE, BRICK_RED, BRICK_RED, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_PURPLE, BRICK_PURPLE, BRICK_NONE},

        {BRICK_RED, BRICK_RED, BRICK_FIRE, BRICK_FIRE, BRICK_NONE,
         BRICK_NONE, BRICK_FIRE, BRICK_FIRE, BRICK_PURPLE, BRICK_PURPLE},

        {BRICK_RED, BRICK_FIRE, BRICK_RED, BRICK_PURPLE, BRICK_ICE,
         BRICK_ICE, BRICK_PURPLE, BRICK_FIRE, BRICK_RED, BRICK_PURPLE},

        {BRICK_NONE, BRICK_RED, BRICK_PURPLE, BRICK_FIRE, BRICK_RED,
         BRICK_RED, BRICK_FIRE, BRICK_PURPLE, BRICK_RED, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_PURPLE, BRICK_RED, BRICK_FIRE,
         BRICK_FIRE, BRICK_PURPLE, BRICK_RED, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_FIRE, BRICK_RED,
         BRICK_RED, BRICK_FIRE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_FIRE,
         BRICK_FIRE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE}};


    static const BrickType layout3[ROWS][COLS] = {

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_BLUE,
         BRICK_BLUE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_BLUE, BRICK_GREEN,
         BRICK_GREEN, BRICK_BLUE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_BLUE, BRICK_ICE, BRICK_RUNE,
         BRICK_RUNE, BRICK_ICE, BRICK_BLUE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_BLUE, BRICK_ICE, BRICK_RUNE, BRICK_LIGHTNING,
         BRICK_LIGHTNING, BRICK_RUNE, BRICK_ICE, BRICK_BLUE, BRICK_NONE},

        {BRICK_BLUE, BRICK_ICE, BRICK_RUNE, BRICK_LIGHTNING, BRICK_STONE,
         BRICK_STONE, BRICK_LIGHTNING, BRICK_RUNE, BRICK_GREEN, BRICK_BLUE},

        {BRICK_NONE, BRICK_BLUE, BRICK_ICE, BRICK_RUNE, BRICK_LIGHTNING,
         BRICK_LIGHTNING, BRICK_RUNE, BRICK_ICE, BRICK_BLUE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_BLUE, BRICK_ICE, BRICK_RUNE,
         BRICK_RUNE, BRICK_ICE, BRICK_BLUE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_BLUE, BRICK_GREEN,
         BRICK_GREEN, BRICK_BLUE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_GREEN,
         BRICK_GREEN, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE}};


    static const BrickType layout4[ROWS][COLS] = {

        {BRICK_WOOD, BRICK_WOOD, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_WOOD, BRICK_WOOD},

        {BRICK_RUNE, BRICK_ICE, BRICK_FIRE, BRICK_FIRE, BRICK_NONE,
         BRICK_NONE, BRICK_FIRE, BRICK_FIRE, BRICK_ICE, BRICK_RUNE},

        {BRICK_FIRE, BRICK_LIGHTNING, BRICK_RUNE, BRICK_ICE, BRICK_STONE,
         BRICK_STONE, BRICK_ICE, BRICK_RUNE, BRICK_LIGHTNING, BRICK_FIRE},

        {BRICK_NONE, BRICK_WOOD, BRICK_FIRE, BRICK_RUNE, BRICK_LOCKED,
         BRICK_LOCKED, BRICK_RUNE, BRICK_FIRE, BRICK_WOOD, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_ICE, BRICK_RUNE, BRICK_LIGHTNING,
         BRICK_LIGHTNING, BRICK_RUNE, BRICK_ICE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_FIRE, BRICK_LIGHTNING, BRICK_RUNE,
         BRICK_RUNE, BRICK_LIGHTNING, BRICK_FIRE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_GREEN, BRICK_YELLOW, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_YELLOW, BRICK_GREEN, BRICK_NONE},

        {BRICK_WOOD, BRICK_WOOD, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_WOOD, BRICK_WOOD},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE}};


    static const BrickType layout5[ROWS][COLS] = {

        {BRICK_NONE, BRICK_LOCKED, BRICK_LIGHTNING, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_LIGHTNING, BRICK_LOCKED, BRICK_NONE},

        {BRICK_STONE, BRICK_LIGHTNING, BRICK_RUNE, BRICK_ICE, BRICK_FIRE,
         BRICK_FIRE, BRICK_ICE, BRICK_RUNE, BRICK_LIGHTNING, BRICK_STONE},

        {BRICK_STONE, BRICK_NONE, BRICK_FIRE, BRICK_FIRE, BRICK_RUNE,
         BRICK_RUNE, BRICK_FIRE, BRICK_FIRE, BRICK_NONE, BRICK_STONE},

        {BRICK_STONE, BRICK_LIGHTNING, BRICK_RUNE, BRICK_FIRE, BRICK_SKULL,
         BRICK_BOOK, BRICK_FIRE, BRICK_RUNE, BRICK_LIGHTNING, BRICK_STONE},

        {BRICK_NONE, BRICK_NONE, BRICK_RUNE, BRICK_FIRE, BRICK_FIRE,
         BRICK_FIRE, BRICK_FIRE, BRICK_RUNE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_LOCKED, BRICK_RUNE, BRICK_FIRE, BRICK_FIRE,
         BRICK_FIRE, BRICK_FIRE, BRICK_RUNE, BRICK_LOCKED, BRICK_NONE},

        {BRICK_STONE, BRICK_STONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_STONE, BRICK_STONE},

        {BRICK_LOCKED, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_LOCKED},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE}};


    static const BrickType layout6[ROWS][COLS] = {

        {BRICK_NONE, BRICK_LOCKED, BRICK_STONE, BRICK_STONE, BRICK_STONE,
         BRICK_STONE, BRICK_STONE, BRICK_STONE, BRICK_LOCKED, BRICK_NONE},

        {BRICK_LOCKED, BRICK_STONE, BRICK_FIRE, BRICK_RUNE, BRICK_ICE,
         BRICK_ICE, BRICK_RUNE, BRICK_FIRE, BRICK_STONE, BRICK_LOCKED},

        {BRICK_STONE, BRICK_STONE, BRICK_NONE, BRICK_SKULL, BRICK_FIRE,
         BRICK_FIRE, BRICK_BOOK, BRICK_NONE, BRICK_STONE, BRICK_STONE},

        {BRICK_LOCKED, BRICK_STONE, BRICK_LIGHTNING, BRICK_RUNE, BRICK_FIRE,
         BRICK_FIRE, BRICK_RUNE, BRICK_LIGHTNING, BRICK_STONE, BRICK_LOCKED},

        {BRICK_NONE, BRICK_STONE, BRICK_STONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_STONE, BRICK_STONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_LOCKED, BRICK_FIRE, BRICK_FIRE,
         BRICK_FIRE, BRICK_FIRE, BRICK_LOCKED, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_STONE, BRICK_STONE,
         BRICK_STONE, BRICK_STONE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE}};


    static const BrickType layout7[ROWS][COLS] = {

        {BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED,
         BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED},

        {BRICK_LOCKED, BRICK_LOCKED, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_LOCKED, BRICK_LOCKED},

        {BRICK_LOCKED, BRICK_STONE, BRICK_NONE, BRICK_FIRE, BRICK_FIRE,
         BRICK_FIRE, BRICK_FIRE, BRICK_NONE, BRICK_STONE, BRICK_LOCKED},

        {BRICK_LOCKED, BRICK_STONE, BRICK_NONE, BRICK_SKULL, BRICK_NONE,
         BRICK_NONE, BRICK_BOOK, BRICK_NONE, BRICK_STONE, BRICK_LOCKED},

        {BRICK_LOCKED, BRICK_STONE, BRICK_NONE, BRICK_RUNE, BRICK_NONE,
         BRICK_NONE, BRICK_RUNE, BRICK_NONE, BRICK_STONE, BRICK_LOCKED},

        {BRICK_LOCKED, BRICK_STONE, BRICK_NONE, BRICK_FIRE, BRICK_FIRE,
         BRICK_FIRE, BRICK_FIRE, BRICK_NONE, BRICK_STONE, BRICK_LOCKED},

        {BRICK_LOCKED, BRICK_LOCKED, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_LOCKED, BRICK_LOCKED},

        {BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED,
         BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED, BRICK_LOCKED},

        {BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE,
         BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE, BRICK_NONE}};


    const BrickType(*layout)[COLS] = layout1;

    if (level == 2)
        layout = layout2;

    if (level == 3)
        layout = layout3;

    if (level == 4)
        layout = layout4;

    if (level == 5)
        layout = layout5;

    if (level == 6)
        layout = layout6;

    if (level == 7)
        layout = layout7;


    for (int r = 0; r < ROWS; r++)
    {
        for (int c = 0; c < COLS; c++)
        {
            float x = startX + c * (bw + gapX);
            float y = startY + r * (bh + gapY);

            initBrick(&bricks[r][c], layout[r][c], x, y, bw, bh);
        }
    }
}
